# Generated by Django 3.2.6 on 2021-10-02 19:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Maqola nomi')),
                ('body', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('author', models.CharField(blank=True, default='Admin', max_length=200, verbose_name='Muallif')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('image', models.ImageField(upload_to='Maqolalar_rasmi/', verbose_name='Maqola rasmi')),
            ],
            options={
                'verbose_name': 'Maqola',
                'verbose_name_plural': 'Maqolalar',
            },
        ),
    ]
