# Generated by Django 3.2.6 on 2021-10-02 19:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='F,I,SH')),
                ('email', models.EmailField(max_length=100, verbose_name='Elektron pochta')),
                ('phone', models.CharField(max_length=20, verbose_name='Telfon raqami')),
                ('types', models.CharField(max_length=150, verbose_name='Qaysi xizmat turi')),
                ('message', models.TextField(verbose_name='Xabari')),
            ],
            options={
                'verbose_name': 'Aloqa',
                'verbose_name_plural': 'Aloqalar',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Ismi')),
                ('message', models.TextField(verbose_name='Xabar')),
                ('blog_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.blog')),
            ],
            options={
                'verbose_name': 'Muhokama',
                'verbose_name_plural': 'Muhokamalar',
            },
        ),
    ]
