# Generated by Django 3.2.6 on 2021-10-03 17:56

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_comment_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Portfolio nomi')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='*')),
                ('author', models.CharField(blank=True, default='Admin', max_length=200, verbose_name='Muallif')),
                ('date', models.DateField(auto_now_add=True, verbose_name="Qo'shilgan vaqti")),
                ('image', models.ImageField(upload_to='Maqolalar_rasmi/', verbose_name='Maqola rasmi')),
                ('body', ckeditor.fields.RichTextField()),
            ],
            options={
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfoliolar',
            },
        ),
    ]
